config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # devise_for :users, controllers: { sessions: 'users/sessions' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "home#index"

   get 'contacts/new'
   post 'contacts/create'
   get 'contacts/list'
   patch 'contacts/update'
 
   post 'contacts/list'
   get 'contacts/show'
   get 'contacts/update'
   get 'contacts/edit'
   get 'contacts/delete'
   post 'contacts/delete'
   post 'contacts/edit'
   get 'contacts/test'
   post 'contacts/test'
   get "send_email" => "contacts#send_email" 
   post "send_email" => "contacts#send_email"
   get 'contacts/email_page'

  get 'picture/new'
  post 'picture/create'
  get 'picture/create'
  get 'picture/delete'
  post 'picture/delete'
  get 'picture/list'

  get 'home/index'
  get 'home/details'
 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  
end

app/models/contact.rb
class Contact < ApplicationRecord
  
    #self.per_page = 5
    #WillPaginate.per_page = 2
    belongs_to :user
    validates_presence_of :firstName, message: 'First Name is Mandatory!' 
    validates_presence_of :lastName, message: 'Last Name is Mandatory!' 
    validates_presence_of :city, message: 'City is Mandatory!' 
    validates_presence_of :address, message: 'Address is Mandatory!' 
    validates :email, format: {with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/}
    validates :phone, length: { is: 10}

    has_one_attached :dp
    
    def dp_thumbnail
        if dp.attached?

          dp.variant(resize_to_limit:[200,200]).processed 
        else
          '/photo.png'
        end    
    end

    def self.search( keywords)
      if keywords 
        where("firstName LIKE ? OR lastName LIKE ? OR id LIKE ?", "%#{keywords}%", "%#{keywords}%", "%#{keywords}%")
      end
    end
 

end

app/models/picture.rb
class Picture < ApplicationRecord
    belongs_to :user
    has_one_attached:pic
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable 
  
  has_many :contacts, dependent: :destroy
  has_one_attached :avatar 
  has_many :pictures, dependent: :destroy

  def avatar_thumbnail
    if avatar.attached?
      
      avatar.variant(resize_to_limit:[200,200]).processed 
    else
      '/default_profile.png'
    end    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?
   
 
    protected

         def configure_permitted_parameters
              devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password , :password_confirmation,:avatar])

              devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :password, :current_password, :avatar])

              
         end

         def after_sign_out_path_for(resource_or_scope)
          new_user_session_path
        end
        
            
       
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    before_action :authenticate_user!
    skip_before_action :verify_authenticity_token

    def list
        p '------contct cntrlr list-------'
       
        if params[:page_size].blank?
            params[:page_size]=5
        end
       if params['search_name'].blank?
        @contacts=current_user.contacts.all.paginate(page:params[:page], :per_page =>params[:page_size] )  
       else    
        @contacts=current_user.contacts.search(params['search_name']).paginate(page:params[:page])
      
        if @contacts.blank?
            puts '--------------nothing to show------------'
        end
        respond_to do |format|
            format.html
            format.pdf do
              render pdf: "Contacts: #(current_user.contacts.all.count)", template: "contacts/list.html.erb"   # Excluding ".pdf" extension.
            end
          end
        
    end

    def show  
        p '--------contct cntrler show-----------'

        @contact=Contact.find(params[:id])  
        p @contact
        respond_to do |format|
            format.html
            format.pdf do
              render pdf: "Contact id: #(@contact.id)", template: "contacts/pdf_page.html.erb"   # Excluding ".pdf" extension.
            end
          end
       end  
        
    end

    def contact_params
        params.require(:contacts).permit(:firstName,:lastName,:address,:city,:phone,:email,:user_id)    
    end 

    def new
        @contact= Contact.new
    end

    def create
        @contact= current_user.contacts.build(contact_param)   
        respond_to do |format|
            if @contact.save
                format.html {redirect_to contacts_new_url(@contact),notice: "A contact is successfully created."}
                format.json {render :show, status: :created, location: @contact}
             else       
                format.html{ render :new, status: :unprocessable_entity}
                format.json{ render json: @contact.errors, status: :unprocessable_entity}
            end   
        end   
    end
    
    def contact_param
        params.require(:contact).permit(:firstName,:lastName,:address,:city,:phone,:email,:dp,:user_id,:favourite)
    end

    def edit
        @contact= Contact.find(params[:id])
    end
    
    def update
        @contact= Contact.find(params[:id]) 
        if @contact.update(contact_param)
            redirect_to :action => 'show', :id =>@contact
        else
            render :action => 'edit' 
        end       
    end
     
    def delete
        Contact.find(params[:id]).destroy
        respond_to do |format|
            format.html { redirect_to contacts_list_path, alert: 'A contact is sucessfully destroyed!'}
            format.json { head :no_content}
        end     
    end

    def send_email
        p '------send_email------'
        p params[:message]
        p params[:email]
        ContactMailer.contact(params[:message],params[:email],params[:sub]).deliver
       
    end
    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @contacts=current_user.contacts.where("contacts.favourite=?","1")
  end

  def new
  end
end

app/controllers/picture_controller.rb
class PictureController < ApplicationController

    def list
        @pictures=current_user.pictures.all
    end
    def show
        @picture = Picture.find(params[:id])
     end
 
    def create
        puts "---------- pic-cntrlr-------- create.........."
        puts picture_param
        @picture=current_user.pictures.build(picture_param)
        respond_to do |format|
            if @picture.save
                format.html {redirect_to picture_new_url(@picture), notice: "A picture is successfully uploaded!"}
                format.json {render :show,status: :created, location: :@picture}
            else
                format.html{render :new, status: :unprocessable_entity}
                format.json{render json: @picture.errors, status: :unprocessable_entity}
            end
        end
    end
    
    def picture_param
        p 'uuuuuuuuuuuu'
        params.require(:picture).permit!
    end

    def new
        @picture= Picture.new
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

    def list
        @users=User.find.all
    end    
end

app/helpers/application_helper.rb
module ApplicationHelper
    def active_class(path)
        if request.path == path
          return 'active'
        else
          return ''
        end
      end
      
end

app/helpers/contacts_helper.rb
module ContactsHelper
   
end

app/helpers/picture_helper.rb
module PictureHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/contacts/edit.html.erb
<div class =""container>
<div class="row">
<div class="col-2">
</div>
<div class="col-8">

<section class="attendance mt-5">
   <div class="attendance-list">
   <center><h1> Update Contact</h1></center>
<%= form_for @contact, :url =>{:action => "update", :id =>@contact} do |form| %>
  <% if @contact.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

   <div class="field form-group">
    <%= form.label :firstName, style: "display: block" %>
    <%= form.text_field :firstName, class: "form-control" %>
  </div>
  <br/>
  <div class="field form-group">
    <%= form.label :lastName, style: "display: block" %>
    <%= form.text_field :lastName, class: "form-control" %>
  </div>
  <br/>
   <div class="field form-group">
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address, class: "form-control" %>
  </div>
  <br/>

  <div class="field form-group">
    <%= form.label :city, style: "display: block" %>
    <%= form.text_field :city, class: "form-control" %>
  </div>
  <br/>
   <div class="field form-group">
    <%= form.label :phone, style: "display: block" %>
    <%= form.number_field :phone, class: "form-control" %>
  </div>
  <br/>
   <div class="field form-group">
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email, class: "form-control" %>
  </div>
  <br/>
  <div class="field form-group">
  <%= form.label :user_id, style: "display: block" %>
  <%= form.text_field :user_id, class: "form-control" ,:readonly =>true%>
  </div> 
   <br/>

  <div class="field form-group">
  <%= form.label :DisplayPicture, style: "display: block" %>
  <%= form.file_field :dp, class: "form-control" %>
</div>
<br/>
   <p align="center">
    <%= form.submit class: "button-21"  %>
  </p>
<% end %>
</div>
</div>
</section >

<div class="col-2">
</div>
</div>

app/views/contacts/email_page.html.erb
<br/><br/>
<div class=" row">
<div class=" col-2"></div> 
<div class="  col-8">
<div class="attendance-list ">
<br/>
<h1>Send Email </h1>
<form id="emailForm"action="/send_email" method="post">
<br/> 
<%= select_tag "email", options_from_collection_for_select(current_user.contacts.all, 'email','email') , { :multiple => true, class:"form-control" }%>
<br/>
<input id="sub" name="sub" class="form-control" size="30"  placeholder="Subject"  type="text" />
<br/>
<textarea name="message" class="form-control" placeholder="Your message" row=6></textarea><br/>
<button type="submit"  onclick="clearForm()"  class='button-21' >Submit</button>
</form>
</div> 
</div> 
<div class=" col-2"></div> 
</div> 
</div> 

<script>

clearForm(){
    alert("hi")
    document.getElementById("emailForm").reset(); 
    document.getElementById("sub").value = "";
    document.getElementById("message").value = "";
}
</script>

app/views/contacts/list.html.erb
<div class="row">

<div class="col-12 ">
<% if @contacts.blank? %>
    <p> No contacts to display</p>
<% else %>

<section class="attendance mt-5">
<div class="attendance-list">


<div class="logo1">
<div class="row">
    <div class="col-9">
    <h1 >Contact List</h1>

    </div>
    <div class="col-3">
    <button class="dropbtn">  <%= link_to "Download PDF", contacts_list_path(format: :pdf),  class: 'nav-link' %></button>
       
    <button class="dropbtn">  <%= link_to "Send Email", contacts_email_page_path,  class: 'nav-link' %></button>
       
    </div>
</div>

<table class="table p-5 ">
<thead>
 <tr>
  <th>Contacts Id</th>
  <th> Name</th>
  <th>Address</th>
  <th>City</th>
  <th>Phone</th>
  <th>Email</th>
  <th>user id</th>  
  <th>Download</th>
  <th>Update</th>
  <th>Delete</th>
  <th>Show</th>

 </tr>
</thead>
<tbody>
 <tr>
  <div  id='show-content'>
    <% @contacts.each do |t| %>
      
        <td><%= t.id %></td>
        <td><%= link_to t.firstName + ' '+ t.lastName, {:action => 'show', :id => t.id} %></td>
       
        <td><%= t.address %></td>
        <td> <%= t.city %></td>
        <td><%= t.phone %></td>
        <td> <%= t.email %></td>
        <td><%= t.user_id %></td>  
        <td><%=link_to 'PDF', contacts_show_path(t , :id => t.id, format: :pdf)  %></td>
        <td><%= button_to 'Update', {:action => 'edit', :id => t.id}  %></td>
        <td><%= button_to 'Delete', {:action => 'delete', :id => t.id}  %></td>
        <td> <a href="#ex1" rel="modal:open" id="showmodal">Show</a><td>
        </tr>
        
    <%end%> 
  </div>
 </tr>  
</tbody>
</table>

</div>
</section>

<%end%>
<br/>

<div class="row">
<div class="col-3">

<div class="pag">
<% if @contacts.length > 0 && @contacts.total_pages > 1 %>
    <div class="page_info">
        <%= page_entries_info @contacts %>
    </div>
<% end %> </div>

</div>
<div class="col-5 ">
    <div class="digg_pagination " >
    <%= will_paginate @contacts , :container => false %>
</div>
</div>

<div class="col-4  mt-1">
<div class="page_info " >
<%= form_tag(contacts_list_path, method: :get) do  %>
    <%= select_tag(:page_size, options_for_select([['Select Pagesize', ],['5', 5], ['7', 7], ['20', 20]], selected: :page_size ),onchange: "this.form.submit();" ) %>
    
<% end %>
</div>
</div>

</div>

</div>


</div>

app/views/contacts/new.html.erb
<div class ="container mt-5 p-5" >
<div class="row">
<div class="col-3" >
</div>
<div class="col-6 border">

<br/><h2 class="text-center">Add Contacts
<br/>

<%= form_for @contact, :url =>{:action => "create", :id =>@contact} do |f| %>
<br/>
  <div class="form-group ">
    <%= f.text_field :firstName ,class:"form-control", placeholder:"First Name"%>
    <h6><%= f.error_message_for(:firstName)%></h6>
  </div>
<br/>

<div class="form-group">
  <%= f.text_field :lastName ,class:"form-control" ,placeholder:"Last Name"%>
  <h6><%= f.error_message_for(:lastName)%> </h6>
</div>
<br/>

<div class="form-group">
  <%= f.text_field :address ,class:"form-control", placeholder:"Address" %>
  <h6><%= f.error_message_for(:address)%> </h6>
</div>
<br/>

<div class="form-group">
<%= f.text_field :city ,class:"form-control", placeholder:"City"%>
<h6><%= f.error_message_for(:city)%> </h6>
</div>
<br/>

<div class="form-group">
<%= f.text_field :phone ,class:"form-control" ,placeholder:"Phone"%>
<h6><%= f.error_message_for(:phone)%> </h6>
</div>
<br/>

<div class="form-group">
<%= f.text_field :email ,class:"form-control", placeholder:"Email" %>
<h6><%= f.error_message_for(:email)%> </h6>
</div>
<br/>

<div class="form-group">
<%= f.file_field :dp ,class:"form-control", placeholder:"Browse image"%>
</div>

<div class="form-group">
<%= f.hidden_field :user_id ,class:"form-control", value:current_user.id %>
</div>
<br/>
<div class="text-center">
<%= f.submit class:'button-21'%>

</div>
<br/>
<% end %>

 </div>
 <div class="col-3">
 </div>
 </div>
 
 </div>    

 

app/views/contacts/pdf_page.html.erb
<div class='row'>
   <div class="col-6 ">
 
   <h1><%= @contact.firstName + ' ' +@contact.lastName %></h1>

   <strong>Address: </strong> <%= @contact.address %><br />
   <strong>City :</strong> <%= @contact.city %><br />
   <strong>Phone: </strong> <%= @contact.phone %><br />
   <strong>Email :</strong> <%= @contact.email %><br />
   <strong>Created Date:</strong> <%= @contact.created_at %><br />
   </div>  
</div>

app/views/contacts/show.html.erb
<div class="container">
<br/><br/>
<div class='row'>
   <div class="col-6 ">
 
   <h1><%= @contact.firstName + ' ' +@contact.lastName %></h1>

   <strong>Address: </strong> <%= @contact.address %><br />
   <strong>City :</strong> <%= @contact.city %><br />
   <strong>Phone: </strong> <%= @contact.phone %><br />
   <strong>Email :</strong> <%= @contact.email %><br />
   <strong>Created Date:</strong> <%= @contact.created_at %><br />
   </div>




   <div class="col-2 ">
   
     <% if @contact.dp.attached? %> 
    
      <%= image_tag(@contact.dp , class:"display_photo") if @contact.dp.attached? %>
     <% else %>
      <%= image_tag("default-avatar-2.png" , class:"display_photo") %>
     <% end %> 
    <br/>  <br/>

<%= form_for @contact, :url =>{:action => "update", :id =>@contact} do |form| %>
  
  <% if @contact.favourite!=1 %>
  <%= form.hidden_field :favourite, class: "form-control",value:'1'%>

  <% else %>
  <%= form.hidden_field :favourite, class: "form-control",value:'0'%>
 
  <% end %>  
  <% if @contact.favourite!=1 %>
 <center> <%= form.submit " Add to Favorites  " ,class:"button-fav" %></center>
  <% else %>
  <center> <%= form.submit "Remove from Favorite" ,class:"button-fav" %></center>
  <% end %>

<% end %>
   </div>
</div>
</div>
<div class="col-4 ">
</div>

<hr/>

<%= link_to 'Back', {:action => 'list'} %> |
<%= link_to 'Update', {:action => 'edit', :id => @contact.id}  %> |
<%= link_to 'Delete', {:action => 'delete', :id => @contact.id} %>  

app/views/contacts/test.html.erb
<%= link_to 'Click Here', "#", data: {toggle: "modal", target: "#my-modal"} %>
<%= link_to "Open modal", "#my-modal", :class => "btn", "data-toggle" => "modal" %>

<div class="modal hide fade" id="my-modal" title="My modal">
  <div class="modal-header">
    <button aria-hidden="true" class="close" data-dismiss="modal" type="button">×</button>
    <h3 id="myModalLabel">Modal header</h3>
  </div>
  <div class="modal-body">
    Modal Body
  </div>
  <div class="modal-footer">
    <button aria-hidden="true" class="btn" data-dismiss="modal">Close</button>
  </div>
</div>

<hr/>


<hr/>

<form id="myform" class="form-wizard">
    <h2 class="form-wizard-heading">BootStap Wizard Form</h2>
    <input type="text" value=""/>
    <input type="submit"/>
</form>

<!-- Modal -->
<div id="bootModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Modal header</h3>
    </div>
    <div class="modal-body">
        <p>One fine body…</p>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
        <button class="btn btn-primary">Save changes</button>
    </div>
</div>
<script type="module">
$('#myform').on('submit', function(ev) {
    $('#bootModal').modal('show'); 

    var data = $(this).serializeObject();
    json_data = JSON.stringify(data);
    $("#results").text(json_data); 
    $(".modal-body").text(json_data); 

    // $("#results").text(data);

    ev.preventDefault();
});
</script>
<br/><br/>

<%= Time.now  %>

<hr/>


<p>If you click on the "Hide" button, I will disappear.</p>

<button id="hide">Hide</button>
<button id="show">Show</button>

app/views/home/_form_errors.html.erb
<div class="alert alert-warning alert-dismissible fade show mt-5 ms-5" role="alert">
  <br/><br/>
  <%= notice%>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/home/_header.html.erb
  <!--Nav bar starts here-->
  <nav>
    <label class="logo"><%= image_tag 'sm.png' ,class:"logimg" %><span class="logo1"> SMartApp</span></label>
    <input type="checkbox" id="check" />
    <label for="check" class="hamberger-btn">
      <i class="fas fa-bars"></i>
    </label>
    <ul>
      
      <% if user_signed_in? %>

      <li> 
      
      <%= form_tag(contacts_list_path, method: :get) do %>
        <%= text_field_tag :search_name, params[:search_name], :placeholder => "Search Contact" %>
         <%= submit_tag "Search" , class:"button" %> 
         <script>
            $("#search_name").bind("ajax:complete", function(event,xhr,status){
            $('#search_name').val(''); 
          }
         </script>
     <% end %>
     
     </li>
     &emsp;
      <li><button class="dropbtn">  <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'nav-link' %></button><li>

      <li>&emsp;
        <div class="dropdown">
        <%= image_tag(current_user.avatar_thumbnail ,class:"profile_photo" ) %>   <%= current_user.name%>
        
          <div class="dropdown-content">
            <%= link_to "Contacts", contacts_list_path  ,class: 'nav-link'%>
            <%= link_to "Add Contacts", contacts_new_path,  class: 'nav-link' %>
            <%= link_to 'Edit Profile', edit_user_registration_path ,  class: 'nav-link' %> 
            
          </div>
        </div>
        
      </li>
      <% else %> 
      <li><button class="dropbtn">  <%= link_to "Sign Up", new_user_registration_path , class: 'nav-link'%></button></li>
      <li>&emsp;
      <li><button class="dropbtn">  <%= link_to "Login", new_user_session_path  , class: 'nav-link'%></button></li>
       
      <% end %>
    
    </ul>
  </nav>
  <!--Nav bar ends here-->

app/views/home/_index_logbox.html.erb
<div class="body">
    <div class="  center index " >
        <div class="card" >
             <div class="card-body">
                <div class="index_banner"><h1 class="card-title "><%= image_tag 'sm.png' ,class:"logimg" %><span class="logo1">SMartApp</span></h1></div>
                <h2 class="card-subtitle mb-2 text-muted logo1">Welcome to <span style="color: #452A5A;">SMartApp !</span></h2>
                <h6><span style="color: #452A5A;">SMartApp !</span> is a first-of-its-kind unifying fusion platform, built from the ground up to make your life easy.</h6>
                <p class="card-text">
                <hr>
                <div class=" logbox row ml-auto mr-auto text-center" >
                    <div class='col-6'>
        
                    <div class=" index_b1 ms-4 p-3 me-5 center " style=" border-color:  #452A5A; color:#452A5A;">
                    
                    <h3><%= link_to 'Create New Account' , new_user_registration_path %></h3>
                         
                    </div>
                    </div>
              
                    <div class='col-6'>
                    <div class=" index_b1 ms-4 me-5 " style="background-color: #452A5A; border-color: #452A5A; color:#e2e1e0;">
                    <h3>Sign In</h3>
                </div>
                </p>
               
            </div>
        </div>

    </div>
</div>   
 

app/views/home/_sidebar.html.erb
<aside class="sidebar">
<div class="field mt-5", style="text-align:center;">
<% if user_signed_in? %>
<%= image_tag(current_user.avatar_thumbnail , class:"display_photo") if current_user.avatar.attached? %>
<% end %>
</div>
  <s_nav class="nav">
    <ul>
  
      <li class="active"><a ><%= link_to 'Welcome' , root_path %></a></li>
      <% if user_signed_in? %>
      <li><a href="#"><%= link_to 'Gallery', picture_list_path %></a></li>
      <% end %>
      <li><a href="#">What We Do</a></li>
      <li><a href="#">Get In Touch</a></li>   
      <li><a href="#"><%= link_to 'Test', contacts_test_path %></a></li>

    </ul>
  </s_nav>
</aside>

app/views/home/index.html.erb
<%#  render 'home/index_logbox' %>


<% if user_signed_in? %>


  <%= render "home/index_signin" %>
 
<% else %>  
 
  <%= render "home/index_logbox" %>

<% end %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Contactapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script src="https://kit.fontawesome.com/6a56f7c0ea.js" SameSite=None></script>

      <!-- Link Swiper's CSS -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/swiper/swiper-bundle.min.css"
    />



    <%= javascript_importmap_tags %>

  </head>

  <body>
  <%= render "home/header" %>
  <main class="main">
     
<%= render 'home/sidebar' %>
  <section class="twitter">
    <div class="container"   >
     
       <% if notice %>
       <p class="alert alert-success "><%= notice %></p>
     <% end %>
     <% if alert %>
       <p class="alert alert-danger"><%= alert %></p>
     <% end %>
     <%= yield %>
     <% if flash %>
     <div id="flash-notice" title="Basic dialog" class="flash-div flash-message">
      
     </div>
   <% end %>
      </div>
  </section>
  </main>

</body>
</html>

app/views/picture/list.html.erb
<div class="attendance-list"><br/>
<h2>Upload New Picture</h2>
<%= link_to'Choose picture' ,picture_create_path %>

</div>
<br/><br/>

<section class="attendance mt-5">
<div class="attendance-list"><br/>
<h2>Gallery</h2>
<br/>
<div class="row2"> 
<% @pictures.each do |t| %>
    <% if t.pic.attached? %>
      <div class="item"> 
        <%= image_tag((t.pic) , :class => "img")%>  
      </div>
    <% end %>   
<% end %>
</div>
</section>
</div>

app/views/picture/new.html.erb
<div class ="container mt-5 p-5" >
<div class="row">
<div class="col-3" >
</div>
<div class="col-6 border">
<br/><h2 class="text-center">Upload Picture
<br/>
<%= form_for @picture, :url=>{:action => "create", :id =>@picture}  do |f| %>   
    <br/>

    <div class="form-group">
        <%= f.text_field :title ,class:"form-control", placeholder:"Title"%>
        <h6><%= f.error_message_for(:title)%> </h6>
    </div>
    <br/>

    <div class="form-group">
        <%= f.text_field :description ,class:"form-control" ,placeholder:"Description"%>
        <h6><%= f.error_message_for(:description)%> </h6>
    </div>
    <br/>

    <div class="form-group">
        <%= f.file_field :pic ,class:"form-control", placeholder:"Browse image"%>
    </div>

    <div class="form-group">
        <%= f.hidden_field :user_id ,class:"form-control", value:current_user.id %>
    </div>
<br/>
<br/>
<div class="text-center">
<%= f.submit class:'button-21'%>

</div>
<br/>
<% end %>    
</div>
 <div class="col-3">
 </div>
 </div>
 
 </div>    